name: CI
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "30 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: build
        run: npm install && npm run build
      - name: Deploy data
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-email: autodepoly
          git-config-name: autodepoly
          folder: data
          branch: dataset
          clean: true
